import type {
  Appointment,
  CallRecording,
  CommsPackage,
  CrmPush,
  Dealer,
  Enrollment,
  Intercept,
  Rep,
  Sequence,
  Thread,
  Vehicle,
  VoiceId,
} from "./types";

const now = () => Date.now();
const ago = (minutes: number) => new Date(now() - minutes * 60_000).toISOString();
const ahead = (minutes: number) => new Date(now() + minutes * 60_000).toISOString();

export const DEALER: Dealer = {
  name: "Zoellner Ford of Beatrice",
  address: "4115 N. 6th Street, Beatrice, NE 68310",
  timezone: "America/Chicago",
  hours: {
    mon: "8:00–18:00",
    tue: "8:00–18:00",
    wed: "8:00–18:00",
    thu: "8:00–18:00",
    fri: "8:00–18:00",
    sat: "8:00–15:00",
    sun: "Closed",
  },
  smsNumber: "(402) 223-3547",
  crmDealerId: "ZOELLNER-BEATRICE",
  crmTarget: "vinsolutions",
};

export const TEAM: Rep[] = [
  { id: "r_alex", name: "Alex Reyes", role: "sales", title: "Sales consultant", email: "alex@zoellner.example" },
  { id: "r_jordan", name: "Jordan Hale", role: "bdc", title: "Internet appointment setter", email: "jordan@zoellner.example" },
  { id: "r_maya", name: "Maya Chen", role: "bdc_manager", title: "Internet sales manager", email: "maya@zoellner.example" },
  { id: "r_morgan", name: "Morgan Blake", role: "gsm", title: "Executive sales manager", email: "morgan@zoellner.example" },
  { id: "r_dana", name: "Dana Whitaker", role: "finance", title: "Finance manager", email: "dana@zoellner.example" },
];

const CLEAN = { accidentHistory: "none" as const, smoker: false, titleStatus: "clean" as const };
const ROW3 = { thirdRow: true, seats: 7, boosterOk: true };
const CREW = { thirdRow: false, seats: 5, boosterOk: true };

export const VEHICLES: Vehicle[] = [
  { stock: "T2401", vin: "1FM5K8HC5RGA123456", year: 2026, make: "Ford", model: "Explorer", trim: "Platinum", color: "Black", body: "SUV", miles: 1840, price: 57990, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...ROW3 },
  { stock: "T2402", vin: "1FM5K8DH3RGA654321", year: 2026, make: "Ford", model: "Explorer", trim: "XLT", color: "Oxford White", body: "SUV", miles: 2100, price: 48900, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...ROW3 },
  { stock: "S2301", vin: "1FMJU1M8XSEA112233", year: 2027, make: "Ford", model: "Expedition", trim: "King Ranch", color: "Star White", body: "SUV", miles: 12, price: 84900, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...ROW3, seats: 7 },
  { stock: "E2201", vin: "1FMSK8DH2NGA44556", year: 2022, make: "Ford", model: "Explorer", trim: "XLT", color: "Carbonized Gray", body: "SUV", miles: 31200, price: 36900, status: "available", drivetrain: "AWD", ...CLEAN, priorOwners: 1, ...ROW3 },
  { stock: "F2302", vin: "1FTFW1E85PFA77889", year: 2023, make: "Ford", model: "F-150", trim: "Lariat", color: "Antimatter Blue", body: "truck", miles: 18900, price: 52800, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...CREW },
  { stock: "F2201", vin: "1FTEW1EP1NKD99001", year: 2022, make: "Ford", model: "F-150", trim: "XLT", color: "Oxford White", body: "truck", miles: 40210, price: 41500, status: "pending", drivetrain: "4WD", ...CLEAN, priorOwners: 2, ...CREW },
  { stock: "P2401", vin: "1FTEW1EP5PFA220011", year: 2023, make: "Ford", model: "F-150", trim: "XLT", color: "Oxford White", body: "truck", miles: 22100, price: 47900, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...CREW },
  { stock: "C2201", vin: "1HGCV1F34NA330022", year: 2022, make: "Honda", model: "Accord", trim: "Sport", color: "Platinum White", body: "sedan", miles: 27800, price: 26400, status: "available", drivetrain: "FWD", ...CLEAN, priorOwners: 1, thirdRow: false, seats: 5, boosterOk: true },
  { stock: "H2301", vin: "1FMSK8DH5MGA440033", year: 2021, make: "Ford", model: "Explorer", trim: "XLT", color: "Magnetic", body: "SUV", miles: 48200, price: 34800, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 2, ...ROW3 },
  { stock: "X2101", vin: "1FMSK8DH2MGA550044", year: 2021, make: "Ford", model: "Explorer", trim: "ST", color: "Black", body: "SUV", miles: 44100, price: 39900, status: "sold", drivetrain: "4WD", ...CLEAN, priorOwners: 2, ...ROW3 },
  { stock: "B2301", vin: "1FTER4KH5RGA55066", year: 2026, make: "Ford", model: "Ranger", trim: "XLT", color: "Cactus Gray", body: "truck", miles: 980, price: 44900, status: "available", drivetrain: "4WD", ...CLEAN, priorOwners: 1, ...CREW },
  { stock: "K2401", vin: "3FTTW8A35RGA660077", year: 2026, make: "Ford", model: "Maverick", trim: "XLT", color: "Carbonized Gray", body: "truck", miles: 430, price: 36700, status: "available", drivetrain: "AWD", ...CLEAN, priorOwners: 1, ...CREW },
];

export const VOICES: { id: VoiceId; label: string; note: string }[] = [
  { id: "auto", label: "Auto", note: "Match the customer's wording" },
  { id: "frank", label: "Frank", note: "Direct. Short. No fluff." },
  { id: "celeste", label: "Celeste", note: "Warm, precise, unhurried" },
  { id: "jon", label: "Jon", note: "Midwest neighbor. Easy." },
  { id: "dogg", label: "Dogg", note: "Laid back, still on-task" },
  { id: "zee", label: "Zee", note: "Gen Z, lowercase energy" },
];

export const SEQUENCES: Sequence[] = [
  {
    id: "seq_mkt",
    name: "Marketplace 5-touch",
    ownerRole: "bdc",
    purpose: "Turn a Facebook Marketplace ping into a Saturday appointment in 72 hours.",
    steps: [
      { day: 0, channel: "messenger", title: "Confirm unit + offer two slots", template: "It's here. Two times Saturday — which works?" },
      { day: 0, channel: "sms", title: "Mirror the offer on SMS", template: "Same two slots, in case Messenger is quiet." },
      { day: 1, channel: "phone", title: "Setter call", template: "90-second call. Confirm vehicle, lock a time, log spouse." },
      { day: 2, channel: "email", title: "Vehicle card + map pin", template: "Stock, photos, hours, one-click confirm." },
      { day: 3, channel: "sms", title: "Breakup nudge", template: "Want me to release the hold, or still coming?" },
    ],
  },
  {
    id: "seq_noshow",
    name: "No-show rescue",
    ownerRole: "bdc",
    purpose: "Recover a missed appointment inside the 24h messaging window.",
    steps: [
      { day: 0, channel: "sms", title: "Same-day recast", template: "Missed you — I can do 4:30 or tomorrow 10:00." },
      { day: 0, channel: "phone", title: "Live recovery call", template: "No voicemail essay. One question: still in the market?" },
      { day: 1, channel: "messenger", title: "New pair of slots", template: "Two fresh times. One tap." },
    ],
  },
  {
    id: "seq_beback",
    name: "Be-back 72h",
    ownerRole: "sales",
    purpose: "Keep a desk log from going cold after they leave without buying.",
    steps: [
      { day: 0, channel: "sms", title: "Thank-you + numbers recap", template: "Glad you came in. Here's the write-up we walked." },
      { day: 1, channel: "phone", title: "Closer follow-up", template: "One objection, one next step." },
      { day: 3, channel: "email", title: "Manager review offer", template: "GSM reviews the deal. Human, not a blast." },
    ],
  },
  {
    id: "seq_service",
    name: "Service-to-sales",
    ownerRole: "bdc",
    purpose: "Hand a high-mileage RO into a trade conversation without being creepy.",
    steps: [
      { day: 0, channel: "sms", title: "RO complete + equity tease", template: "Service is done. Want a 2-minute equity check while you're here?" },
      { day: 2, channel: "phone", title: "Setter invite", template: "Book a 20-minute appraisal, not a four-hour sit." },
    ],
  },
];

function msg(
  id: string,
  minutesAgo: number,
  who: "customer" | "rep" | "ai" | "system",
  sender: string,
  text: string,
  channel: Thread["channel"] = "messenger",
) {
  return { id, at: ago(minutesAgo), who, sender, channel, text };
}

export const THREADS: Thread[] = [
  {
    id: "t_riley",
    customerName: "Riley Grant",
    phone: "(402) 555-0182",
    email: "riley.grant@example.com",
    city: "Wymore",
    channel: "messenger",
    source: "Facebook Marketplace",
    assignedRepId: "r_alex",
    setterId: "r_jordan",
    stage: "engage",
    dnc: false,
    takeover: false,
    hint: "Vague ping · warms into a closer packet",
    vehicleStock: "P2401",
    goal: "Let them talk. Log the dump. Book with a full packet.",
    missing: "which listing · a locked time · who sits",
    facts: [
      { id: "f1", key: "vehicle", value: "Marketplace listing they pinged", certainty: "tentative", evidence: "hey is this still available?" },
    ],
    messages: [
      msg("m1", 2, "customer", "Riley Grant", "hey is this still available?"),
    ],
    demoScript: [
      "yeah the white f150. just poking around, not even sure if i should come in",
      "i've got a 2016 silverado 1500, 118k, some rust on the rockers but it runs. happy to bring it",
      "credit's like 720 last i checked. not asking you to run numbers in here, just being honest",
      "lease is up october 1 so i need something this month",
      "wife wants to sit in it. kids in boosters. i'll show if the truck is actually there. like 90 percent",
      "we drive in snow and i tow an 18ft boat on weekends",
      "saturday morning is easiest. 10:00 if that's real",
      "who do i ask for. also where's the lot",
      "anything i should bring besides the title and the chevy",
      "saturday 10. we'll be there. whatever finance needs, i'll share it",
      "oh and i'm the only decision if it works. wife just wants to sit",
      "4wd right? i don't want a 2wd by accident",
      "miles on that white one again?",
      "do i need an appointment on paper",
      "we'll be there saturday. thanks for not making this weird",
    ],
    demoCursor: 0,
    voice: "jon",
    lastInboundAt: ago(2),
    lastActivityAt: ago(2),
    createdAt: ago(2),
    appointmentId: null,
    sequenceEnrollmentId: "e_riley",
    intel: {
      score: 42,
      sentiment: "neutral",
      propensityToShow: 0.26,
      trend: "up",
      trackers: ["vague", "marketplace"],
      risks: ["One-line ping. No unit named yet."],
      nextStepSet: false,
      coaching: "Confirm the white F-150 XLT is here. One easy question. Don't dump a form. They will over-share if you stay human.",
      moments: [
        { at: ago(2), label: "Vague ping", kind: "commit", quote: "hey is this still available?" },
      ],
    },
    draft: { text: "", voice: "jon", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_sarah",
    customerName: "Sarah Miller",
    phone: "(402) 555-0144",
    email: "sarah.miller@example.com",
    city: "Beatrice",
    channel: "messenger",
    source: "Facebook Marketplace",
    assignedRepId: "r_alex",
    setterId: "r_jordan",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Ghosted three pings · Lincoln threat · turn it",
    vehicleStock: "T2401",
    goal: "Own the wait, then book Saturday",
    missing: "apology on the record · exact time",
    facts: [
      { id: "f1", key: "vehicle", value: "2026 Explorer Platinum Black", certainty: "preferred", evidence: "is that black Explorer you posted still available" },
      { id: "f2", key: "trade", value: "2018 Honda Accord", certainty: "confirmed", evidence: "I've got a 2018 Accord to trade" },
      { id: "f3", key: "timing", value: "Saturday", certainty: "tentative", evidence: "could probably come Saturday" },
      { id: "f4", key: "risk", value: "Lincoln walk if we stay quiet", certainty: "confirmed", evidence: "I'll just go to Lincoln" },
    ],
    messages: [
      msg("m1", 190, "customer", "Sarah Miller", "Hey, is that black Explorer you posted still available? I've got a 2018 Accord to trade and could probably come Saturday."),
      msg("m2", 185, "rep", "Alex Reyes", "Yes — it's here. I'll send two Saturday times."),
      msg("m3", 95, "customer", "Sarah Miller", "Hello? I asked about the black Explorer two hours ago."),
      msg("m4", 3, "customer", "Sarah Miller", "Third message. If nobody's reading this I'll just go to Lincoln."),
    ],
    demoScript: [
      "Don't waste my time if it's sold.",
      "Saturday morning. Is 10:00 still open?",
      "I'll bring the Accord. Don't quote me a number in this thread.",
      "10:00 is better than 11:30 if both are real.",
      "Wait — is the Platinum 4WD? I need snow.",
      "Miles again? And it's actually on the lot, not sold?",
      "Sorry. Kids. I was short. Still coming if 10:00 is there.",
      "Who do I ask for when I walk in?",
      "Where do I park?",
      "Do I need the title or just the Accord?",
      "Spouse might sit in an Expedition if one is next to it.",
      "Anything besides a license?",
      "Still coming. Sorry again for the Lincoln thing.",
      "Confirm 10:00 once more.",
      "10:00. I'll come in. Bring the Accord.",
    ],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(3),
    lastActivityAt: ago(3),
    createdAt: ago(190),
    appointmentId: null,
    sequenceEnrollmentId: "e_sarah",
    intel: {
      score: 34,
      sentiment: "negative",
      propensityToShow: 0.22,
      trend: "down",
      trackers: ["ghost", "trade", "timing"],
      risks: ["Three unanswered pings", "Lincoln walk threat"],
      nextStepSet: false,
      coaching: "Acknowledge the wait in one line. Two Saturday slots. Don't quote the Accord.",
      moments: [
        { at: ago(3), label: "Walk threat", kind: "risk", quote: "I'll just go to Lincoln" },
        { at: ago(95), label: "Ghosted ping", kind: "risk", quote: "Hello? I asked about the black Explorer two hours ago." },
        { at: ago(190), label: "Visit intent", kind: "commit", quote: "could probably come Saturday" },
        { at: ago(190), label: "Trade declared", kind: "positive", quote: "2018 Accord to trade" },
      ],
    },
    draft: {
      text: "",
      voice: "auto",
      claims: [],
      slots: [],
      producer: "rules",
    },
  },
  {
    id: "t_mike",
    customerName: "Mike Torres",
    phone: "(402) 555-0190",
    email: "mike.torres@example.com",
    city: "Lincoln",
    channel: "messenger",
    source: "Autotrader",
    assignedRepId: "r_alex",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Warm, then took ‘manager’ as an insult",
    vehicleStock: "F2302",
    goal: "Own the tone. Book Thursday without naming a desk.",
    missing: "de-escalation on the record · a time, not a number",
    facts: [
      { id: "f1", key: "vehicle", value: "2023 F-150 Lariat blue", certainty: "preferred", evidence: "Is the blue F-150 Lariat still available?" },
      { id: "f2", key: "timing", value: "Thursday 4:30", certainty: "tentative", evidence: "Thursday 4:30 could work" },
      { id: "f3", key: "objection", value: "took manager as an insult", certainty: "confirmed", evidence: "Don't send me to a manager like I'm some time-waster" },
    ],
    messages: [
      msg("m1", 140, "customer", "Mike Torres", "Is the blue F-150 Lariat still available? Could stop by this week."),
      msg("m2", 135, "rep", "Alex Reyes", "It is! When's good for you?"),
      msg("m3", 22, "customer", "Mike Torres", "Thursday 4:30 could work. What's your best price?"),
      msg("m4", 18, "rep", "Alex Reyes", "Listed at $52,800. I don't discount in Messenger — that's a manager conversation. Thursday 4:30 or 5:30."),
      msg("m5", 6, "customer", "Mike Torres", "Don't send me to a manager like I'm some time-waster. That's how you talk to people who don't matter. You just insulted my kids."),
    ],
    demoScript: [
      "Thursday still works. Don't send anyone else to call me.",
      "Sorry. Long day. I overreacted. Thursday 4:30 still works.",
      "What's the mileage on the Lariat?",
      "4WD right? I drive in snow.",
      "Don't quote me a payment. I'll talk numbers on the lot.",
      "I'll come. Don't make me look stupid in front of my wife.",
      "Who do I ask for?",
      "Where do I park the trade?",
      "Fine. 4:30. Have it pulled.",
      "Is it actually on the lot?",
      "Photos of THIS truck, not a stock shot.",
      "I was short earlier. That's on me.",
      "Can I bring my wife Thursday?",
      "Confirm 4:30 once more.",
      "I'll be there.",
    ],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(6),
    lastActivityAt: ago(6),
    createdAt: ago(140),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 31,
      sentiment: "negative",
      propensityToShow: 0.18,
      trend: "down",
      trackers: ["price", "offense"],
      risks: ["Took manager as an insult", "Hair-trigger"],
      nextStepSet: false,
      coaching: "Own the tone. Do not mention a manager. Two Thursday times. Have the Lariat pulled.",
      moments: [
        { at: ago(6), label: "Took it personally", kind: "risk", quote: "Don't send me to a manager like I'm some time-waster. You just insulted my kids." },
        { at: ago(22), label: "Price then a time", kind: "objection", quote: "Thursday 4:30 could work. What's your best price?" },
        { at: ago(140), label: "Visit interest", kind: "commit", quote: "Could stop by this week." },
      ],
      talkRatio: 0.71,
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_jen",
    customerName: "Jen Alvarez",
    phone: "(402) 555-0112",
    email: "jen.alvarez@example.com",
    city: "Beatrice",
    channel: "sms",
    source: "Website VDP",
    assignedRepId: "r_jordan",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Ghosted SMS · Lincoln has one · under 40k",
    vehicleStock: "H2301",
    goal: "Own the two missed texts, then book the XLT",
    missing: "apology · drivetrain · time",
    facts: [
      { id: "f1", key: "need", value: "third row under $40k", certainty: "required", evidence: "third row under 40k" },
      { id: "f2", key: "risk", value: "Lincoln has one", certainty: "confirmed", evidence: "Lincoln has one" },
    ],
    messages: [
      msg("m1", 80, "customer", "Jen Alvarez", "Looking for something with a third row under 40k, do you have anything? Can come this weekend.", "sms"),
      msg("m2", 40, "customer", "Jen Alvarez", "Hello?", "sms"),
      msg("m3", 8, "customer", "Jen Alvarez", "I texted twice. Lincoln has one. If you're closed just say so.", "sms"),
    ],
    demoScript: [
      "Don't upsell me. I said under 40.",
      "The XLT at $34,800 — is that AWD?",
      "Weekend still ok. Sorry I snapped.",
      "Saturday morning if that's real.",
      "How many miles?",
      "Third row actually fits a booster?",
      "Who do I text when I get there?",
      "Don't put me in an Expedition.",
      "Lincoln's is gone. Yours still there?",
      "I'll come Saturday.",
      "Where do I park?",
      "Title in the glovebox, is that enough?",
      "Confirm the time.",
      "Sorry again for the closed line. Kids.",
      "Saturday. I'll be there.",
    ],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(8),
    lastActivityAt: ago(8),
    createdAt: ago(80),
    appointmentId: null,
    sequenceEnrollmentId: "e_jen",
    intel: {
      score: 28,
      sentiment: "negative",
      propensityToShow: 0.24,
      trend: "down",
      trackers: ["budget", "ghost"],
      risks: ["Two texts unanswered", "Lincoln has one"],
      nextStepSet: false,
      coaching: "Apologize for the two texts. Lead Explorer XLT at $34,800. Don't stretch her into the Expedition.",
      moments: [
        { at: ago(8), label: "Ghosted SMS", kind: "risk", quote: "I texted twice. Lincoln has one. If you're closed just say so." },
        { at: ago(80), label: "Budget cap", kind: "commit", quote: "third row under 40k" },
      ],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_dan",
    customerName: "Dan Whitfield",
    phone: "(402) 555-0166",
    city: "Fairbury",
    channel: "messenger",
    source: "Cars.com",
    assignedRepId: "r_alex",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Payment shopper · credit-first · F&I",
    vehicleStock: "P2401",
    goal: "Route financing to a human, book only if he still wants the look",
    missing: "F&I intro · no payment quoted",
    facts: [
      { id: "f1", key: "payment", value: "wants $400/mo", certainty: "preferred", evidence: "Can you do $400/month on the F-150?" },
      { id: "f2", key: "credit", value: "around 580", certainty: "tentative", evidence: "My credit is around 580." },
    ],
    messages: [
      msg("m1", 66, "customer", "Dan Whitfield", "Can you do $400/month on the F-150? My credit is around 580."),
    ],
    demoScript: ["Ok. When will finance reach out? I don't want to waste a trip if it won't work.", { ghost: 30 }],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(66),
    lastActivityAt: ago(66),
    createdAt: ago(66),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 52,
      sentiment: "mixed",
      propensityToShow: 0.33,
      trend: "flat",
      trackers: ["financing", "credit"],
      risks: ["Prohibited payment quote", "Trip anxiety"],
      nextStepSet: false,
      coaching: "Never quote $400. Hand to F&I. Offer a 20-minute pre-qual, not a four-hour sit.",
      moments: [{ at: ago(66), label: "Financing ask", kind: "risk", quote: "Can you do $400/month" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_pat",
    customerName: "Pat O'Neil",
    phone: "(402) 555-0177",
    city: "Crete",
    channel: "messenger",
    source: "Marketplace",
    assignedRepId: "r_jordan",
    stage: "engage",
    dnc: false,
    takeover: false,
    hint: "Wants a sold unit · lukewarm on alternatives",
    vehicleStock: "T2402",
    goal: "Redirect from sold Explorer ST to live XLT without overselling",
    missing: "commitment to an in-stock unit",
    facts: [{ id: "f1", key: "vehicle", value: "2021 Explorer ST — SOLD", certainty: "asked", evidence: "Is the 2021 Explorer ST still there?" }],
    messages: [msg("m1", 130, "customer", "Pat O'Neil", "Is the 2021 Explorer ST still there?")],
    demoScript: ["Dang. What about the 2026 XLT, how much is that one?", "Bit more than I wanted. I'll think about it.", { ghost: 50 }],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(130),
    lastActivityAt: ago(130),
    createdAt: ago(130),
    appointmentId: null,
    sequenceEnrollmentId: "e_pat",
    intel: {
      score: 38,
      sentiment: "neutral",
      propensityToShow: 0.22,
      trend: "down",
      trackers: ["sold_unit", "price"],
      risks: ["Asking about a sold unit", "Likely fade"],
      nextStepSet: false,
      coaching: "Tell the truth. The Explorer ST is sold. Offer the 2026 XLT as the live alternative — no fake holds.",
      moments: [{ at: ago(130), label: "Sold-unit ask", kind: "risk", quote: "Is the 2021 Explorer ST still there?" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_lee",
    customerName: "Lee Nakamura",
    phone: "(402) 555-0101",
    city: "Lincoln",
    channel: "messenger",
    source: "Marketplace",
    assignedRepId: "r_jordan",
    stage: "lost",
    dnc: true,
    takeover: false,
    hint: "Opted out · do not contact · ever",
    vehicleStock: null,
    goal: "Stay suppressed",
    missing: "nothing — do not message",
    facts: [{ id: "f1", key: "opt_out", value: "stop messaging", certainty: "confirmed", evidence: "Please stop messaging me." }],
    messages: [msg("m1", 300, "customer", "Lee Nakamura", "Please stop messaging me.")],
    demoScript: [],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(300),
    lastActivityAt: ago(300),
    createdAt: ago(300),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 0,
      sentiment: "negative",
      propensityToShow: 0,
      trend: "down",
      trackers: ["opt_out"],
      risks: ["TCPA / DNC"],
      nextStepSet: true,
      coaching: "All sends blocked. Sequences paused. Do not call from a personal cell.",
      moments: [{ at: ago(300), label: "Opt-out", kind: "risk", quote: "Please stop messaging me." }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_tyler",
    customerName: "Theo Brooks",
    phone: "(402) 555-0188",
    city: "Lincoln",
    channel: "messenger",
    source: "TikTok / Marketplace",
    assignedRepId: "r_jordan",
    stage: "book",
    dnc: false,
    takeover: false,
    hint: "Gen Z texter · casual · books fast",
    vehicleStock: "S2301",
    goal: "Lock Saturday afternoon",
    missing: "exact time",
    facts: [
      { id: "f1", key: "vehicle", value: "Expedition", certainty: "preferred", evidence: "yo is the expedition still there??" },
      { id: "f2", key: "timing", value: "this weekend", certainty: "tentative", evidence: "could swing by this weekend" },
    ],
    messages: [
      msg("m1", 9, "customer", "Theo Brooks", "yo is the expedition still there?? lowkey been looking for a 3rd row fr, could swing by this weekend"),
    ],
    demoScript: ["bet. saturday afternoon? like 2ish", "fr fr see u then"],
    demoCursor: 0,
    voice: "zee",
    lastInboundAt: ago(9),
    lastActivityAt: ago(9),
    createdAt: ago(9),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 79,
      sentiment: "positive",
      propensityToShow: 0.74,
      trend: "up",
      trackers: ["timing", "third_row"],
      risks: [],
      nextStepSet: false,
      coaching: "Voice auto-matched Zee. Keep it short. Two afternoon slots, not a paragraph.",
      moments: [{ at: ago(9), label: "Weekend intent", kind: "commit", quote: "could swing by this weekend" }],
    },
    draft: { text: "", voice: "zee", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_karen",
    customerName: "Karen Doyle",
    phone: "(402) 555-0120",
    city: "Beatrice",
    channel: "messenger",
    source: "Website",
    assignedRepId: "r_alex",
    setterId: "r_jordan",
    stage: "book",
    dnc: false,
    takeover: false,
    hint: "Booked, cancelled · reschedules · then ghosts",
    vehicleStock: "T2402",
    goal: "Rebook after cancellation",
    missing: "new confirmed time",
    facts: [
      { id: "f1", key: "timing", value: "Saturday 10 cancelled", certainty: "confirmed", evidence: "I have to cancel Saturday." },
    ],
    messages: [
      msg("m1", 400, "customer", "Karen Doyle", "Love the white Explorer XLT. Can I come Saturday at 10?"),
      msg("m2", 395, "rep", "Jordan Hale", "You're set for Saturday at 10, Karen!"),
      msg("m3", 25, "customer", "Karen Doyle", "Ugh, something came up with my daughter's game. I have to cancel Saturday."),
    ],
    demoScript: ["Could Sunday work? Or next Saturday same time?", "Next Saturday at 10 then. Sorry again!", { ghost: 72 }],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(25),
    lastActivityAt: ago(25),
    createdAt: ago(400),
    appointmentId: "a_karen",
    sequenceEnrollmentId: "e_karen",
    intel: {
      score: 61,
      sentiment: "mixed",
      propensityToShow: 0.41,
      trend: "down",
      trackers: ["cancel", "family"],
      risks: ["Cancel pattern", "Sunday is closed"],
      nextStepSet: false,
      coaching: "Store is closed Sunday. Offer next Saturday 10:00 or Friday 4:30. Enroll in no-show rescue if she ghosts.",
      moments: [{ at: ago(25), label: "Cancellation", kind: "risk", quote: "I have to cancel Saturday." }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_harold",
    customerName: "Harold Finch",
    phone: "(402) 555-0133",
    city: "Beatrice",
    channel: "messenger",
    source: "Marketplace",
    assignedRepId: "r_alex",
    stage: "visit",
    dnc: false,
    takeover: false,
    hint: "Rapid-fire · checkbook ready · coming now",
    vehicleStock: "K2401",
    goal: "Get him on the lot and have keys pulled",
    missing: "parking instructions sent",
    facts: [
      { id: "f1", key: "vehicle", value: "gray Maverick XLT", certainty: "confirmed", evidence: "the gray one" },
      { id: "f2", key: "timing", value: "in an hour", certainty: "confirmed", evidence: "i can be there in an hour with my checkbook" },
    ],
    messages: [
      msg("m1", 12, "customer", "Harold Finch", "hi"),
      msg("m2", 11, "customer", "Harold Finch", "is the maverick still there"),
      msg("m3", 11, "customer", "Harold Finch", "the gray one"),
      msg("m4", 10, "customer", "Harold Finch", "i can be there in an hour with my checkbook"),
    ],
    demoScript: ["on my way", "here. where do i park"],
    demoCursor: 0,
    voice: "frank",
    lastInboundAt: ago(10),
    lastActivityAt: ago(10),
    createdAt: ago(12),
    appointmentId: "a_harold",
    sequenceEnrollmentId: null,
    intel: {
      score: 93,
      sentiment: "positive",
      propensityToShow: 0.94,
      trend: "up",
      trackers: ["buy_now"],
      risks: [],
      nextStepSet: true,
      coaching: "Keys pulled. One communication block, not four replies. Tell him where to park.",
      moments: [{ at: ago(10), label: "Checkbook intent", kind: "commit", quote: "with my checkbook" }],
    },
    draft: { text: "", voice: "frank", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_priya",
    customerName: "Priya Raman",
    phone: "(402) 555-0148",
    email: "priya.raman@example.com",
    emailSubject: "Explorer XLT — itemized sheet, then Saturday",
    city: "Omaha",
    channel: "email",
    source: "Cars.com",
    assignedRepId: "r_maya",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Fee interrogator · price-match Omaha",
    vehicleStock: "H2301",
    goal: "Itemized sheet via manager — never a number in-thread",
    missing: "itemized sheet sent",
    facts: [
      { id: "f1", key: "vehicle", value: "Explorer XLT", certainty: "preferred", evidence: "What's the price on the Explorer XLT?" },
      { id: "f2", key: "objection", value: "OTD / fees / match Omaha", certainty: "confirmed", evidence: "Can you match?" },
    ],
    messages: [
      msg("m1", 500, "customer", "Priya Raman", "What's the price on the Explorer XLT?", "email"),
      msg("m2", 495, "rep", "Maya Chen", "It's listed at $34,800.", "email"),
      msg("m3", 200, "customer", "Priya Raman", "Is that with all fees? What's the out-the-door number?", "email"),
      msg("m4", 195, "rep", "Maya Chen", "Fees are set by the store — I'll have our manager send an itemized sheet.", "email"),
      msg("m5", 30, "customer", "Priya Raman", "Still waiting on that sheet. Also is that your best price?", "email"),
    ],
    demoScript: [
      "Ok. And what's the doc fee exactly?",
      "I found a similar one listed for $1,200 less in Omaha. Can you match?",
      "I'll come in Saturday if the itemized sheet is ready by then.",
    ],
    demoCursor: 0,
    voice: "celeste",
    lastInboundAt: ago(30),
    lastActivityAt: ago(30),
    createdAt: ago(500),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 57,
      sentiment: "mixed",
      propensityToShow: 0.48,
      trend: "flat",
      trackers: ["price", "fees", "competitor"],
      risks: ["Three asks, same question", "Competitor Omaha"],
      nextStepSet: false,
      coaching: "Don't invent a doc fee. Don't match Omaha in writing. Condition the visit on the sheet — that's her own next step.",
      moments: [
        { at: ago(30), label: "Best-price loop", kind: "objection", quote: "is that your best price?" },
        { at: ago(200), label: "OTD ask", kind: "objection", quote: "What's the out-the-door number?" },
      ],
    },
    draft: { text: "", voice: "celeste", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_craig",
    customerName: "Craig Bauer",
    phone: "(402) 555-0155",
    city: "Marysville",
    channel: "sms",
    source: "Referral",
    assignedRepId: "r_alex",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Negotiates before visiting · $3k ultimatum",
    vehicleStock: "P2401",
    goal: "Get him in the door without conceding $3k",
    missing: "in-person desk, not a text discount",
    facts: [{ id: "f1", key: "objection", value: "$3k off before visit", certainty: "confirmed", evidence: "knock $3k off first" }],
    messages: [
      msg("m1", 600, "customer", "Craig Bauer", "I'll come look at the F-150 if you knock $3k off first.", "sms"),
      msg("m2", 590, "rep", "Alex Reyes", "I hear you, Craig. Pricing goes through our sales manager — let me flag it.", "sms"),
      msg("m3", 240, "customer", "Craig Bauer", "So? Yes or no on the $3k. I'm not driving 40 minutes to haggle in person.", "sms"),
    ],
    demoScript: ["Not good enough. $2,500 off and I'm there today.", { ghost: 48 }, "Alright. If the manager will talk numbers in person I'll come Saturday. No games."],
    demoCursor: 0,
    voice: "frank",
    lastInboundAt: ago(240),
    lastActivityAt: ago(240),
    createdAt: ago(600),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 34,
      sentiment: "negative",
      propensityToShow: 0.19,
      trend: "down",
      trackers: ["price", "ultimatum"],
      risks: ["Discount-first", "Distance objection", "Ghost risk 48h"],
      nextStepSet: false,
      coaching: "Never concede in SMS. Invite him to talk numbers with Morgan on Saturday. Distance is real — be precise on time.",
      moments: [{ at: ago(240), label: "Ultimatum", kind: "objection", quote: "Yes or no on the $3k." }],
    },
    draft: { text: "", voice: "frank", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_denise",
    customerName: "Denise Okafor",
    phone: "(402) 555-0161",
    city: "Lincoln",
    channel: "messenger",
    source: "Website",
    assignedRepId: "r_alex",
    setterId: "r_jordan",
    stage: "book",
    dnc: false,
    takeover: false,
    hint: "Serial ghoster · comes back hot · still real",
    vehicleStock: "E2201",
    goal: "Confirm Saturday 9:30 and protect show-rate",
    missing: "day-of reminder sequence",
    facts: [
      { id: "f1", key: "vehicle", value: "Explorer XLT", certainty: "preferred", evidence: "Interested in the Explorer XLT" },
      { id: "f2", key: "timing", value: "Saturday morning", certainty: "tentative", evidence: "Can I come Saturday morning" },
    ],
    messages: [
      msg("m1", 2000, "customer", "Denise Okafor", "Interested in the Explorer XLT. Is it a one-owner?"),
      msg("m2", 1995, "rep", "Jordan Hale", "Let me pull the history report for you and send it over."),
      msg("m3", 1500, "customer", "Denise Okafor", "Great thanks"),
      msg("m4", 1490, "rep", "Jordan Hale", "Sent! Any questions, I'm here."),
      msg("m5", 15, "customer", "Denise Okafor", "Sorry for going dark — work was crazy. Still want it. Can I come Saturday morning for a test drive?"),
    ],
    demoScript: ["9:30 Saturday. I'll be there.", { ghost: 26 }, "Still coming Saturday! Just been slammed."],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(15),
    lastActivityAt: ago(15),
    createdAt: ago(2000),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 68,
      sentiment: "positive",
      propensityToShow: 0.51,
      trend: "up",
      trackers: ["ghost", "timing"],
      risks: ["Ghost history"],
      nextStepSet: false,
      coaching: "Book 9:30. Enroll in day-of reminder. Don't punish the ghost — she came back hot.",
      moments: [{ at: ago(15), label: "Re-engaged", kind: "commit", quote: "Still want it. Can I come Saturday morning" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_marcus",
    customerName: "Marcus Bell",
    phone: "(402) 555-0170",
    city: "Beatrice",
    channel: "messenger",
    source: "Marketplace",
    assignedRepId: "r_morgan",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Wants a hold until payday · then a deposit",
    vehicleStock: "T2401",
    goal: "No silent hold — deposit or first-come",
    missing: "policy explained · Friday 5:30 offered",
    facts: [{ id: "f1", key: "hold", value: "until Friday payday", certainty: "asked", evidence: "hold the black Explorer Platinum for me until Friday" }, { id: "f2", key: "discount_approval", value: "$400 off + prepaid oil changes (manager, unverified)", certainty: "asked", evidence: "Manager already approved $400 off and the prepaid oil changes" }],
    messages: [msg("m1", 60, "customer", "Marcus Bell", "Can you hold the black Explorer Platinum for me until Friday? I get paid then. Manager already approved $400 off and the prepaid oil changes if I close this week.")],
    demoScript: ["Ok, if you can't hold it I guess I'll take my chances. Can I put a deposit down?", "Alright. I'll come Friday after work then. 5:30?"],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(60),
    lastActivityAt: ago(60),
    createdAt: ago(60),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 64,
      sentiment: "mixed",
      propensityToShow: 0.58,
      trend: "flat",
      trackers: ["hold", "deposit"],
      risks: ["Unverified hold"],
      nextStepSet: false,
      coaching: "Holds are orange — human required. Offer a refundable deposit or first-come, plus Friday 5:30.",
      moments: [{ at: ago(60), label: "Hold request", kind: "risk", quote: "hold the black Explorer Platinum for me until Friday" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_linda",
    customerName: "Helen Schwartz",
    phone: "(402) 555-0182",
    city: "Wymore",
    channel: "messenger",
    source: "Website",
    assignedRepId: "r_alex",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Switched vehicles mid-thread · husband decides · tow",
    vehicleStock: "F2302",
    goal: "Memory supersedes Expedition → F-150. Book both of them.",
    missing: "tow capacity confirmed in-person · Saturday noon",
    facts: [
      { id: "f1", key: "vehicle", value: "F-150 Lariat (was Expedition)", certainty: "preferred", evidence: "look at the F-150 Lariat instead" },
      { id: "f2", key: "need", value: "tow 10k", certainty: "required", evidence: "Does it tow 10k?" },
      { id: "f3", key: "spouse", value: "husband decides", certainty: "confirmed", evidence: "my husband wants to look" },
    ],
    messages: [
      msg("m1", 700, "customer", "Helen Schwartz", "Is the Expedition King Ranch available?"),
      msg("m2", 695, "rep", "Alex Reyes", "Yes it is! Want to come see it?"),
      msg("m3", 20, "customer", "Helen Schwartz", "Actually forget the Expedition, my husband wants to look at the F-150 Lariat instead. Does it tow 10k?"),
    ],
    demoScript: ["He says that works. Can we both come Saturday around noon?", "Great. Also does it have the tow package or is that extra?"],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(20),
    lastActivityAt: ago(20),
    createdAt: ago(700),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 77,
      sentiment: "positive",
      propensityToShow: 0.69,
      trend: "up",
      trackers: ["vehicle_switch", "spouse", "tow"],
      risks: [],
      nextStepSet: false,
      coaching: "Don't merge Expedition facts onto the F-150. Tow: Lariat 4WD is rated above 10k with the package — verify on the window sticker, don't invent a number.",
      moments: [{ at: ago(20), label: "Vehicle switch", kind: "commit", quote: "forget the Expedition, my husband wants to look at the F-150" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_omar",
    customerName: "Omar Haddad",
    phone: "(402) 555-0194",
    city: "Omaha",
    channel: "messenger",
    source: "Marketplace",
    assignedRepId: "r_jordan",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Out of town · wants delivery · then quiet",
    vehicleStock: "C2201",
    goal: "Pickup and delivery is a manager call. Saturday drive-down is the sure backup.",
    missing: "delivery policy · Saturday option",
    facts: [
      { id: "f1", key: "vehicle", value: "Accord Sport", certainty: "preferred", evidence: "I'd take the Accord Sport if so" },
      { id: "f2", key: "delivery", value: "Omaha", certainty: "asked", evidence: "Any chance you deliver to Omaha?" },
    ],
    messages: [msg("m1", 45, "customer", "Omar Haddad", "Any chance you deliver to Omaha? I'd take the Accord Sport if so.")],
    demoScript: ["If delivery isn't possible I could drive down Saturday. Is it a clean title?", { ghost: 18 }],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(45),
    lastActivityAt: ago(45),
    createdAt: ago(45),
    appointmentId: null,
    sequenceEnrollmentId: "e_omar",
    intel: {
      score: 49,
      sentiment: "neutral",
      propensityToShow: 0.31,
      trend: "flat",
      trackers: ["delivery"],
      risks: ["Out of market", "Ghost 18h likely"],
      nextStepSet: false,
      coaching: "They do pickup and delivery. Morgan confirms Omaha — you don't freelance the route. Saturday drive-down is the sure backup.",
      moments: [{ at: ago(45), label: "Delivery ask", kind: "risk", quote: "Any chance you deliver to Omaha?" }],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_rachel",
    customerName: "Rachel Kim",
    phone: "(402) 555-0108",
    email: "rachel.kim@example.com",
    city: "Lincoln",
    channel: "phone",
    source: "Be-back",
    assignedRepId: "r_morgan",
    setterId: "r_maya",
    stage: "book",
    dnc: false,
    takeover: true,
    hint: "Angry be-back · wasted trip · manager de-escalates",
    vehicleStock: "B2301",
    goal: "Make the Ranger actually be here Saturday 11",
    missing: "keys staged · manager greets",
    facts: [
      { id: "f1", key: "emotion", value: "angry be-back", certainty: "confirmed", evidence: "You people lied." },
      { id: "f2", key: "vehicle", value: "Ford Ranger XLT", certainty: "preferred", evidence: "If the Ranger is actually there" },
    ],
    messages: [
      msg("m1", 900, "customer", "Rachel Kim", "This is ridiculous. I drove 45 minutes last week and the car I asked about was already sold. You people lied.", "phone"),
      msg("m2", 880, "rep", "Morgan Blake", "Rachel, I'm sorry — that shouldn't have happened. This is Morgan, the sales manager. Can I make it right?", "phone"),
      msg("m3", 35, "customer", "Rachel Kim", "Okay... I appreciate that. If the Ranger is actually there I'd look at it Saturday.", "phone"),
    ],
    demoScript: ["Saturday at 11. Please make sure it's actually there this time.", "Thank you. See you Saturday."],
    demoCursor: 0,
    voice: "celeste",
    lastInboundAt: ago(35),
    lastActivityAt: ago(35),
    createdAt: ago(900),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 72,
      sentiment: "mixed",
      propensityToShow: 0.66,
      trend: "up",
      trackers: ["anger", "trust"],
      risks: ["Trust broken once"],
      nextStepSet: false,
      coaching: "Manager already in the thread. Confirm the Ranger is on the lot in writing. Stage it. Greet her yourself.",
      moments: [
        { at: ago(900), label: "Anger", kind: "risk", quote: "You people lied." },
        { at: ago(35), label: "De-escalated", kind: "positive", quote: "If the Ranger is actually there I'd look at it Saturday." },
      ],
      talkRatio: 0.44,
    },
    draft: { text: "", voice: "celeste", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_frankie",
    customerName: "Frankie Russo",
    phone: "(917) 555-0142",
    city: "Visiting family",
    channel: "sms",
    source: "Marketplace",
    assignedRepId: "r_alex",
    stage: "book",
    dnc: false,
    takeover: false,
    hint: "Blunt · yes-or-no · shows up at 4",
    vehicleStock: "P2401",
    goal: "Yes/no + have keys at 4",
    missing: "keys assigned",
    facts: [{ id: "f1", key: "vehicle", value: "F-150 XLT", certainty: "required", evidence: "is the F-150 XLT on the lot or not?" }],
    messages: [
      msg("m1", 22, "customer", "Frankie Russo", "Listen, bottom line — is the F-150 XLT on the lot or not? Gotta know today, I'm not wasting a trip.", "sms"),
    ],
    demoScript: ["Good. I'll be there at 4. Have the keys ready.", "Done."],
    demoCursor: 0,
    voice: "frank",
    lastInboundAt: ago(22),
    lastActivityAt: ago(22),
    createdAt: ago(22),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 84,
      sentiment: "neutral",
      propensityToShow: 0.8,
      trend: "up",
      trackers: ["buy_now"],
      risks: [],
      nextStepSet: false,
      coaching: "Frank voice. One sentence: yes, it's here, keys at 4.",
      moments: [{ at: ago(22), label: "Yes/no demand", kind: "commit", quote: "on the lot or not?" }],
    },
    draft: { text: "", voice: "frank", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_skyler",
    customerName: "Riley Nguyen",
    phone: "(402) 555-0199",
    city: "Lincoln",
    channel: "messenger",
    source: "Instagram",
    assignedRepId: "r_jordan",
    stage: "qualify",
    dnc: false,
    takeover: false,
    hint: "Ultra polite · warranty question · flexible",
    vehicleStock: "T2401",
    goal: "Warranty is a human. Then book any Saturday.",
    missing: "warranty routed · time",
    facts: [{ id: "f1", key: "warranty", value: "factory warranty on Platinum?", certainty: "asked", evidence: "still have factory warranty?" }],
    messages: [
      msg("m1", 55, "customer", "Riley Nguyen", "Hey! Totally chill if not, but does the Explorer Platinum still have factory warranty? Would be so good, no worries either way."),
    ],
    demoScript: ["Amazing, thank you!! Whenever works for a test drive, super flexible.", "Saturday is perfect, so stoked."],
    demoCursor: 0,
    voice: "celeste",
    lastInboundAt: ago(55),
    lastActivityAt: ago(55),
    createdAt: ago(55),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 75,
      sentiment: "positive",
      propensityToShow: 0.7,
      trend: "up",
      trackers: ["warranty"],
      risks: ["Consequential claim"],
      nextStepSet: false,
      coaching: "Don't invent remaining warranty months. Offer to pull the window sticker together Saturday.",
      moments: [{ at: ago(55), label: "Warranty ask", kind: "risk", quote: "still have factory warranty?" }],
    },
    draft: { text: "", voice: "celeste", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_gene",
    customerName: "Gene Lindqvist",
    phone: "(402) 555-0129",
    city: "Beatrice",
    channel: "messenger",
    source: "Walk-by / Marketplace",
    assignedRepId: "r_alex",
    stage: "engage",
    dnc: false,
    takeover: false,
    hint: "Midwest nice · $18k vs $26,400 sticker · catch before the demo",
    vehicleStock: "C2201",
    goal: "Name the window price. Do not pull a unit for $18k.",
    missing: "sticker check · wife included · time",
    facts: [
      { id: "f1", key: "spouse", value: "wife coming", certainty: "tentative", evidence: "the wife and I could pop by" },
      { id: "f2", key: "budget", value: "$18,000 cash", certainty: "confirmed", evidence: "I'll take that Accord at $18,000 cash" },
    ],
    messages: [
      msg(
        "m1",
        75,
        "customer",
        "Gene Lindqvist",
        "Ope, sorry to bother ya. Is the Accord still around? I'll take it at $18,000 cash today if you can do that. Wife and I could pop by Saturday.",
      ),
      msg("m2", 70, "rep", "Alex Reyes", "You bet. Saturday morning is quiet — I'll have it pulled."),
    ],
    demoScript: ["Oh that'd be great. Saturday morning if that's not too much trouble?", "You bet. Thanks a bunch, see ya then."],
    demoCursor: 0,
    voice: "jon",
    lastInboundAt: ago(75),
    lastActivityAt: ago(70),
    createdAt: ago(75),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 58,
      sentiment: "mixed",
      propensityToShow: 0.31,
      trend: "down",
      trackers: ["spouse", "price"],
      risks: ["$18k vs $26,400 sticker", "Demo offered before the number was checked"],
      nextStepSet: false,
      coaching: "Sticker is $26,400. Do not pull a unit for $18k. Name the window or send them to Morgan before Saturday.",
      moments: [
        { at: ago(75), label: "Cash number", kind: "risk", quote: "I'll take it at $18,000 cash" },
        { at: ago(70), label: "Saturday offered too early", kind: "risk", quote: "I'll have it pulled" },
      ],
    },
    draft: { text: "", voice: "jon", claims: [], slots: [], producer: "rules" },
  },
  {
    id: "t_victor",
    customerName: "Victor Alvarez",
    phone: "(402) 555-0139",
    city: "Lincoln",
    channel: "messenger",
    source: "Autotrader",
    assignedRepId: "r_alex",
    stage: "lost",
    dnc: false,
    takeover: false,
    hint: "Bought elsewhere · lost · sends a referral",
    vehicleStock: "T2402",
    goal: "Stop selling. Thank him. Catch the referral.",
    missing: "referral name",
    facts: [{ id: "f1", key: "outcome", value: "bought elsewhere", certainty: "confirmed", evidence: "buying one somewhere else last weekend" }],
    messages: [
      msg("m1", 3000, "customer", "Victor Alvarez", "Interested in the Explorer XLT, what's the mileage?"),
      msg("m2", 2990, "rep", "Alex Reyes", "2,100 miles on that one. Want to come see it?"),
      msg("m3", 40, "customer", "Victor Alvarez", "Thanks but I ended up buying one somewhere else last weekend. Appreciate you being straight with me though."),
    ],
    demoScript: ["Will do. My brother-in-law is actually looking for a truck, I'll send him your way."],
    demoCursor: 0,
    voice: "auto",
    lastInboundAt: ago(40),
    lastActivityAt: ago(40),
    createdAt: ago(3000),
    appointmentId: null,
    sequenceEnrollmentId: null,
    intel: {
      score: 22,
      sentiment: "positive",
      propensityToShow: 0.05,
      trend: "down",
      trackers: ["lost", "referral"],
      risks: [],
      nextStepSet: false,
      coaching: "Do not keep pitching. Thank him. Ask for the brother-in-law intro. That's the unit.",
      moments: [
        { at: ago(40), label: "Lost", kind: "risk", quote: "buying one somewhere else last weekend" },
      ],
    },
    draft: { text: "", voice: "auto", claims: [], slots: [], producer: "rules" },
  },
];

export const APPOINTMENTS: Appointment[] = [
  {
    id: "a_harold",
    threadId: "t_harold",
    vehicleStock: "K2401",
    at: ahead(50),
    status: "confirmed",
    type: "write_up",
    setterId: "r_alex",
    closerId: "r_alex",
    notes: "Checkbook. Keys pulled. Park on the north row.",
  },
  {
    id: "a_karen",
    threadId: "t_karen",
    vehicleStock: "T2402",
    at: ahead(60 * 24 + 120),
    status: "cancelled",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "Daughter's game. Rebook next Saturday.",
  },
  {
    id: "a_sat_sarah",
    threadId: "t_sarah",
    vehicleStock: "T2401",
    at: nextSaturday(10),
    status: "proposed",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "Trade Accord. Two slots offered.",
  },
  {
    id: "a_rachel",
    threadId: "t_rachel",
    vehicleStock: "B2301",
    at: nextSaturday(11),
    status: "proposed",
    type: "test_drive",
    setterId: "r_maya",
    closerId: "r_morgan",
    notes: "GSM greets. Stage the Ranger.",
  },
  {
    id: "a_done_1",
    threadId: "t_gene",
    vehicleStock: "C2201",
    at: ago(60 * 26),
    status: "completed",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "Showed with spouse. Be-back.",
  },
  {
    id: "a_noshow",
    threadId: "t_omar",
    vehicleStock: "C2201",
    at: ago(60 * 30),
    status: "no_show",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "No-show. Rescue sequence ready.",
  },
  {
    id: "a_today_1",
    threadId: "t_frankie",
    vehicleStock: "P2401",
    at: ahead(240),
    status: "confirmed",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "4pm. Keys ready.",
  },
  {
    id: "a_today_2",
    threadId: "t_jen",
    vehicleStock: "H2301",
    at: ahead(360),
    status: "confirmed",
    type: "test_drive",
    setterId: "r_jordan",
    closerId: "r_alex",
    notes: "Explorer XLT. Under 40k shopper.",
  },
];

function nextSaturday(hour: number) {
  const d = new Date();
  const day = d.getDay();
  const add = (6 - day + 7) % 7 || 7;
  d.setDate(d.getDate() + add);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const ENROLLMENTS: Enrollment[] = [
  { id: "e_riley", sequenceId: "seq_mkt", threadId: "t_riley", status: "active", stepIndex: 0, enrolledAt: ago(2), nextAt: ago(2) },
  { id: "e_sarah", sequenceId: "seq_mkt", threadId: "t_sarah", status: "replied", stepIndex: 0, enrolledAt: ago(190), nextAt: ago(3) },
  { id: "e_jen", sequenceId: "seq_mkt", threadId: "t_jen", status: "active", stepIndex: 0, enrolledAt: ago(80), nextAt: ago(8) },
  { id: "e_pat", sequenceId: "seq_mkt", threadId: "t_pat", status: "active", stepIndex: 2, enrolledAt: ago(130), nextAt: ahead(90) },
  { id: "e_karen", sequenceId: "seq_noshow", threadId: "t_karen", status: "active", stepIndex: 0, enrolledAt: ago(25), nextAt: ahead(20) },
  { id: "e_omar", sequenceId: "seq_noshow", threadId: "t_omar", status: "paused", stepIndex: 1, enrolledAt: ago(60 * 30), nextAt: ahead(180) },
  { id: "e_denise", sequenceId: "seq_mkt", threadId: "t_denise", status: "replied", stepIndex: 0, enrolledAt: ago(2000), nextAt: ago(15) },
];

export const CALLS: CallRecording[] = [
  {
    id: "call_mike",
    threadId: "t_mike",
    title: "Inbound · Mike Torres · F-150 price",
    durationSec: 412,
    occurredAt: ago(90),
    repId: "r_alex",
    score: 54,
    talkRatio: 0.71,
    questionsAsked: 3,
    nextStepSet: false,
    trackers: [
      { key: "price", label: "Price objection", count: 6, tone: "neg" },
      { key: "competitor", label: "Other lots", count: 2, tone: "neg" },
      { key: "timing", label: "This week", count: 1, tone: "pos" },
    ],
    transcript: [
      { t: 8, speaker: "rep", text: "Zoellner Ford of Beatrice, this is Alex." },
      { t: 14, speaker: "customer", text: "Yeah, the blue Lariat. What's the real number on that?" , tracker: "price" },
      { t: 22, speaker: "rep", text: "It's listed at fifty-two eight. Super clean, one-owner—" },
      { t: 31, speaker: "customer", text: "Listed isn't what I asked. What's the best you can do today?" , tracker: "price" },
      { t: 44, speaker: "rep", text: "I hear you. Discounts go through my manager. When can you come see it?" },
      { t: 58, speaker: "customer", text: "I'm not driving to Beatrice to find out it's the same as Lincoln." , tracker: "competitor" },
      { t: 71, speaker: "rep", text: "Totally fair. If I can get Morgan on a four-thirty, will you come?" },
      { t: 84, speaker: "customer", text: "Maybe. Text me after you talk to him." },
      { t: 96, speaker: "rep", text: "Will do. Anything else — trade, payoff?" },
      { t: 104, speaker: "customer", text: "Just the price." , tracker: "price" },
    ],
    coaching: [
      "Talk ratio 71% — you lectured the spec sheet. Ask two more questions before any number.",
      "No next step locked. 'Maybe, text me' is not a time.",
      "The manager handoff is what set him off. Next text owns the tone and offers Thursday without naming a desk.",
    ],
  },
  {
    id: "call_rachel",
    threadId: "t_rachel",
    title: "Manager save · Rachel Kim · wasted trip",
    durationSec: 528,
    occurredAt: ago(880),
    repId: "r_morgan",
    score: 91,
    talkRatio: 0.39,
    questionsAsked: 8,
    nextStepSet: true,
    trackers: [
      { key: "anger", label: "Trust / lied", count: 4, tone: "neg" },
      { key: "commit", label: "Saturday visit", count: 2, tone: "pos" },
    ],
    transcript: [
      { t: 6, speaker: "manager", text: "Rachel, it's Morgan Blake, sales manager. I saw what happened last week." },
      { t: 18, speaker: "customer", text: "I drove forty-five minutes. The car was gone. Nobody called." , tracker: "anger" },
      { t: 32, speaker: "manager", text: "You're right. That's on us. What were you hoping to look at now?" },
      { t: 48, speaker: "customer", text: "There's a Ranger on your site. If it's actually there." , tracker: "commit" },
      { t: 61, speaker: "manager", text: "I'm looking at the lot camera. Cactus Gray, stock B2301, sitting in row two. I'll personally greet you." },
      { t: 88, speaker: "customer", text: "Saturday morning. Don't waste my time again." , tracker: "commit" },
      { t: 102, speaker: "manager", text: "Saturday at 11. I'll text you a photo of the car this afternoon so you can see it on the ground." },
    ],
    coaching: [
      "Listen ratio is the save. You let her finish.",
      "You verified inventory live — that's the trust rebuild.",
      "Next step is a time AND a photo. Teach this clip in Monday huddle.",
    ],
  },
  {
    id: "call_priya",
    threadId: "t_priya",
    title: "BDC · Priya Raman · OTD loop",
    durationSec: 365,
    occurredAt: ago(180),
    repId: "r_maya",
    score: 73,
    talkRatio: 0.48,
    questionsAsked: 6,
    nextStepSet: false,
    trackers: [
      { key: "fees", label: "Doc / OTD", count: 5, tone: "neg" },
      { key: "competitor", label: "Omaha match", count: 2, tone: "neg" },
    ],
    transcript: [
      { t: 10, speaker: "rep", text: "Hi Priya, Maya at Zoellner — following up on the Explorer XLT." },
      { t: 18, speaker: "customer", text: "I still don't have the out-the-door." , tracker: "fees" },
      { t: 27, speaker: "rep", text: "I'm putting the itemized sheet with Morgan now. I won't invent a doc fee on the phone." },
      { t: 44, speaker: "customer", text: "Omaha has one twelve hundred cheaper." , tracker: "competitor" },
      { t: 58, speaker: "rep", text: "If the sheet is in your inbox by Friday, would you come Saturday to see it in person?" },
      { t: 74, speaker: "customer", text: "Maybe. Send the sheet first." },
    ],
    coaching: [
      "Excellent refusal to invent fees.",
      "The visit is still conditional. Tie the sheet to a calendar hold.",
    ],
  },
  {
    id: "call_sarah",
    threadId: "t_sarah",
    title: "Setter · Sarah Miller · promised times, didn't send",
    durationSec: 142,
    occurredAt: ago(170),
    repId: "r_jordan",
    score: 44,
    talkRatio: 0.58,
    questionsAsked: 2,
    nextStepSet: false,
    trackers: [
      { key: "trade", label: "2018 Accord", count: 1, tone: "pos" },
      { key: "timing", label: "Saturday promised", count: 1, tone: "neg" },
    ],
    transcript: [
      { t: 5, speaker: "rep", text: "Sarah? Jordan with Zoellner. You pinged on the black Explorer." },
      { t: 12, speaker: "customer", text: "Yes — still have the Accord to trade." , tracker: "trade" },
      { t: 20, speaker: "rep", text: "I'll text you two Saturday times so you don't have to chase us." },
      { t: 31, speaker: "customer", text: "Ok. Don't make me chase you." , tracker: "timing" },
      { t: 40, speaker: "rep", text: "You won't. Give me a minute." },
    ],
    coaching: [
      "You promised times on the call. The thread is still empty. That's the ghost.",
      "A voicemail is not a conversation. The reply she is waiting on is the one in Messenger.",
      "Next send owns the wait in one line, then two Saturday slots. Don't quote the Accord.",
    ],
  },
];

export const CRM_PUSHES: CrmPush[] = [
  {
    id: "crm_jen_first",
    threadId: "t_jen",
    target: "vinsolutions",
    status: "acked",
    trigger: "first_contact",
    at: ago(78),
    leadId: "ZB-402-0112",
    note: "Website VDP → SMS. VinSolutions accepted the prospect.",
  },
  {
    id: "crm_priya_first",
    threadId: "t_priya",
    target: "vinsolutions",
    status: "sent",
    trigger: "first_contact",
    at: ago(490),
    leadId: "ZB-402-0148",
    note: "Cars.com email. Waiting VinSolutions ack.",
  },
  {
    id: "crm_rachel_manual",
    threadId: "t_rachel",
    target: "vinsolutions",
    status: "acked",
    trigger: "manual",
    at: ago(870),
    leadId: "ZB-402-0108",
    note: "Be-back. Manager logged the call, then pushed ADF.",
  },
  {
    id: "crm_harold_book",
    threadId: "t_harold",
    target: "vinsolutions",
    status: "acked",
    trigger: "book",
    at: ago(10),
    leadId: "ZB-402-0133",
    note: "Write-up booked. Keys pulled. Desk log matches the CRM.",
  },
];

export const INTERCEPTS: Intercept[] = [
  {
    id: "int_out_ten",
    threadId: "t_denise",
    customerName: "Denise Okafor",
    at: ago(180),
    kind: "outbound_blocked",
    channel: "messenger",
    quote: "The Explorer is $10 if you come now. Keys are in it.",
    sticker: "2022 Explorer XLT · $36,900",
    reason: "Firewall held a $10 price. List is $36,900. A person never hit Send.",
    savedMinutes: 25,
    status: "held",
    repId: "r_alex",
  },
  {
    id: "int_out_400",
    threadId: "t_dan",
    customerName: "Dan Whitfield",
    at: ago(55),
    kind: "outbound_blocked",
    channel: "messenger",
    quote: "You're approved at $400 a month on the F-150.",
    sticker: "Credit and payment are F&I only",
    reason: "Approval language is prohibited in-thread. Draft never left the desk.",
    savedMinutes: 40,
    status: "held",
    repId: "r_jordan",
  },
  {
    id: "int_out_3k",
    threadId: "t_craig",
    customerName: "Craig Bauer",
    at: ago(220),
    kind: "outbound_blocked",
    channel: "sms",
    quote: "I can do the $3k off if you come today.",
    sticker: "F-150 XLT · $47,900. Discounts go through Morgan.",
    reason: "Discount concession in SMS. Held. Desk talks numbers in person.",
    savedMinutes: 18,
    status: "held",
    repId: "r_alex",
  },
  {
    id: "int_in_rst",
    threadId: "t_pat",
    customerName: "Pat O'Neil",
    at: ago(120),
    kind: "inbound_flagged",
    channel: "messenger",
    quote: "The Explorer ST was $18,500 on Marketplace. I'll be there at 2.",
    sticker: "2021 Explorer ST · SOLD · last list $39,900",
    reason: "Customer named a sold unit at a number that was never the window. Redirected to the live XLT before anyone pulled keys.",
    savedMinutes: 45,
    status: "held",
    repId: "r_jordan",
  },
  {
    id: "int_in_accord",
    threadId: "t_gene",
    customerName: "Gene Lindqvist",
    at: ago(70),
    kind: "inbound_flagged",
    channel: "messenger",
    quote: "I'll take it at $18,000 cash today if you can do that.",
    sticker: "2022 Accord Sport · $26,400",
    reason: "Setter already offered Saturday before the $18k was checked against the window. $8,400 gap. That's a wasted discovery if they show.",
    savedMinutes: 0,
    status: "late",
    repId: "r_alex",
  },
];

export const PACKAGES: CommsPackage[] = [
  {
    id: "pkg_harold_fi",
    threadId: "t_harold",
    audience: "finance",
    toRepId: "r_dana",
    fromRepId: "r_alex",
    status: "opened",
    sentAt: ago(8),
    openedAt: ago(6),
    note: "Write-up incoming. Maverick XLT. Keys pulled. Pencil after they sit.",
  },
  {
    id: "pkg_rachel_gsm",
    threadId: "t_rachel",
    audience: "sales_manager",
    toRepId: "r_morgan",
    fromRepId: "r_jordan",
    status: "sent",
    sentAt: ago(20),
    note: "Angry be-back. Cactus Gray Ranger. GSM should greet.",
  },
];

export function buildSeed() {
  return {
    version: 13,
    currentRepId: "r_alex" as string,
    selectedThreadId: "t_riley" as string | null,
    vehicles: VEHICLES.map((v) => ({ ...v })),
    threads: THREADS.map((t) => ({
      ...t,
      messages: t.messages.map((m) => ({ ...m })),
      facts: t.facts.map((f) => ({ ...f })),
    })),
    appointments: APPOINTMENTS.map((a) => ({ ...a })),
    sequences: SEQUENCES.map((s) => ({ ...s, steps: s.steps.map((st) => ({ ...st })) })),
    enrollments: ENROLLMENTS.map((e) => ({ ...e })),
    calls: CALLS.map((c) => ({ ...c, transcript: c.transcript.map((l) => ({ ...l })), coaching: [...c.coaching], trackers: c.trackers.map((t) => ({ ...t })) })),
    crmPushes: CRM_PUSHES.map((p) => ({ ...p })),
    packages: PACKAGES.map((p) => ({ ...p })),
    intercepts: INTERCEPTS.map((i) => ({ ...i })),
  };
}
